better fix for ip_queue (revert)
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/alpine@4801 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/bunnicula b/mvvm/hier/usr/bin/bunnicula
--- a/mvvm/hier/usr/bin/bunnicula
+++ b/mvvm/hier/usr/bin/bunnicula
@@ -22,7 +22,10 @@ procset() {
 }
 
 # check ip_queue
-if [ -f /proc/net/ip_queue && "`grep Peer /proc/net/ip_queue  | awk '{ print $4 }'`" != "0" ] ; then
+if [ ! -f /proc/net/ip_queue ]; then
+    echo "ERROR: kernel does not have IP_NF_QUEUE" >& 2
+    exit 1
+elif [ "`grep Peer /proc/net/ip_queue  | awk '{ print $4 }'`" != "0" ] ; then
     echo "ERROR: ip_queue allocated, exiting" >&2
     exit 1
 fi
