bunnicula script update
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/alpine/alpine@924 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/bunnicula b/mvvm/hier/usr/bin/bunnicula
--- a/mvvm/hier/usr/bin/bunnicula
+++ b/mvvm/hier/usr/bin/bunnicula
@@ -7,27 +7,35 @@ JAVA_HOME=${JAVA_HOME:-/opt/java}
 
 ## Configure IPV4 parameters
 
-# Not optional, complain if fail
-echo 1  > /proc/sys/net/ipv4/ip_forward
-if [ $? != 0 ] ; then exit 1 ; fi
-echo 1  > /proc/sys/net/ipv4/ip_nonlocal_bind
-if [ $? != 0 ] ; then exit 1 ; fi
-echo "3000   9000" > /proc/sys/net/ipv4/ip_local_port_range
-if [ $? != 0 ] ; then exit 1 ; fi
+procset() {
+    if [ -f $1 ] ; then
+        echo $2 > $1 ;
+        if [ $? != 0 ] ; then 
+            echo "WARNING: Failed to set proc setting \"$1\""  >&2
+            if [ "$3" != "" ] ; then
+                exit 1
+            fi
+        fi
+    else
+        echo "WARNING: Missing proc setting \"$1\"" >&2
+    fi
+}
 
+# check ip_queue
+if [ "`grep Peer /proc/net/ip_queue  | awk '{ print $4 }'`" != "0" ] ; then 
+    echo "ERROR: ip_queue allocated, exiting" >&2
+    exit 1
+fi
+
+# Not Optional
+procset /proc/sys/net/ipv4/ip_forward 1 1
+procset /proc/sys/net/ipv4/ip_nonlocal_bind 1 1
+procset /proc/sys/net/ipv4/ip_local_port_range "3000   9000" 1
 # Optional
-if [ -f /proc/sys/net/ipv4/tcp_synack_retries ] ; then
-    echo 0  > /proc/sys/net/ipv4/tcp_synack_retries ;
-fi
-if [ -f /proc/sys/net/ipv4/tcp_syncookies ] ; then
-    echo 1  > /proc/sys/net/ipv4/tcp_syncookies ;
-fi
-if [ -f /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait ] ; then
-    echo 30 > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait ;
-fi
-if [ -f /proc/sys/net/ipv4/ip_queue_maxlen ]; then
-    echo 16384 > /proc/sys/net/ipv4/ip_queue_maxlen ;
-fi
+procset /proc/sys/net/ipv4/tcp_synack_retries 0
+procset /proc/sys/net/ipv4/tcp_syncookies 1
+procset /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait 30
+procset /proc/sys/net/ipv4/ip_queue_maxlen 16384
 
 # remove tomcat persisted sessions
 find @PREFIX@ -name SESSIONS.ser -exec rm -f '{}' ';'
