added download and install failure
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/alpine@2274 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/mkg b/mvvm/hier/usr/bin/mkg
--- a/mvvm/hier/usr/bin/mkg
+++ b/mvvm/hier/usr/bin/mkg
@@ -95,8 +95,18 @@ if [ -z $prefix ] ; then
         cat $aptlist >>$APT_LOG
         echo "END PACKAGE LIST" >>$APT_LOG
 
-        cat $aptlist | awk '{ print $1 }' \
-            | xargs wget -P /var/cache/apt/archives >>$APT_LOG 2>&1
+        for u in $(cat $aptlist | awk '{ print $1 }' | sed "s/'//g"); do
+            echo "downloading: $u" >>$APT_LOG
+            dltmp=$(mktemp -d)
+            wget --progress=dot -P "$dltmp" "$u" >>$APT_LOG 2>&1
+            if [ $? -eq 0 ]; then
+                mv $dltmp/* /var/cache/apt/archives
+                echo "DOWNLOAD SUCCEEDED: $u" >>$APT_LOG
+            else
+                echo "DOWNLOAD FAILED: $u" >>$APT_LOG
+            fi
+            rm -r $dltmp
+        done
 
         aptlog "installing: \"$2-transform\""
         # XXX the way i create mackage name is wrong:
