Works now.
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/alpine@9073 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/mvactivate b/mvvm/hier/usr/bin/mvactivate
--- a/mvvm/hier/usr/bin/mvactivate
+++ b/mvvm/hier/usr/bin/mvactivate
@@ -12,27 +12,30 @@ if [ -f $ACTIVATION_KEY_FILE ] ; then
     exit 2
 fi
 
-$KEY_VERIFICATION $REG_KEY 2> /dev/null
-VERIFY_RES="$?"
-if [ "$VERIFY_RES" -eq 1 ]; then
-    echo "Key is invalid: $REG_KEY"
-    exit 1
-fi
-if [ "$VERIFY_RES" -ne 0 ]; then
-    echo "Error validating registration.  Unable to continue."
-    exit 2
-fi
+# don't do anything for CD installs w/ initial fake key
+if [ ! -f $CD_INSTALL ] && [ $REG_KEY = $FAKE_KEY ] ; then
+  $KEY_VERIFICATION $REG_KEY 2> /dev/null
+  VERIFY_RES="$?"
+  if [ "$VERIFY_RES" -eq 1 ]; then
+      echo "Key is invalid: $REG_KEY"
+      exit 1
+  fi
+  if [ "$VERIFY_RES" -ne 0 ]; then
+      echo "Error validating registration.  Unable to continue."
+      exit 2
+  fi
 
-# If we get here, the key is good.
-echo "Key is valid"
+  # If we get here, the key is good.
+  echo "Key is valid"
 
-# This next will fail if testing on development machines, which is "a good thing"
-echo "Installing sources list"
-cat @MVVM_HOME@/conf/etc/apt_sources.list | sed "s/XXX_REG_KEY_XXX/$REG_KEY/" > @PREFIX@/etc/apt/sources.list
+  # This next will fail if testing on development machines, which is "a good thing"
+  echo "Installing sources list"
+  cat @MVVM_HOME@/conf/etc/apt_sources.list | sed "s/XXX_REG_KEY_XXX/$REG_KEY/" > @PREFIX@/etc/apt/sources.list
 
-if [ -f "$CD_INSTALL" ]; then
-    echo "Adjusting sources list for CD install"
-    sed -i -e 's/release\.untangle\.com/release-cd.untangle.com/' @PREFIX@/etc/apt/sources.list
+  if [ -f "$CD_INSTALL" ]; then
+      echo "Adjusting sources list for CD install"
+      sed -i -e 's/release\.untangle\.com/release-cd.untangle.com/' @PREFIX@/etc/apt/sources.list
+  fi
 fi
 
 # Do this last
