SHould be good this time.
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/alpine@9452 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/mvactivate b/mvvm/hier/usr/bin/mvactivate
--- a/mvvm/hier/usr/bin/mvactivate
+++ b/mvvm/hier/usr/bin/mvactivate
@@ -22,23 +22,25 @@ if [ -n "$REG_KEY" ] ; then # the install wizard is calling us
   if [[ ! -f $ACTIVATION_KEY_FILE_TMP ]] ; then
     echo $REG_KEY > $ACTIVATION_KEY_FILE_TMP
   fi
+
+  if [[ $REG_KEY != $FAKE_KEY ]] ; then
+    $KEY_VERIFICATION $REG_KEY 2> /dev/null
+    VERIFY_RES="$?"
+    if [ "$VERIFY_RES" -eq 1 ]; then
+	echo "Key is invalid: $REG_KEY"
+	exit 1
+    fi
+    if [ "$VERIFY_RES" -ne 0 ]; then
+	echo "Error validating registration.  Unable to continue."
+	exit 2
+    fi
+
+    # If we get here, the key is good.
+    echo "Key is valid"
+  fi
 else
   # we're being called through mvvm.sh, and the right key is in the 
   # activation file already
-  REG_KEY=`cat $ACTIVATION_KEY_FILE`
-  $KEY_VERIFICATION $REG_KEY 2> /dev/null
-  VERIFY_RES="$?"
-  if [ "$VERIFY_RES" -eq 1 ]; then
-      echo "Key is invalid: $REG_KEY"
-      exit 1
-  fi
-  if [ "$VERIFY_RES" -ne 0 ]; then
-      echo "Error validating registration.  Unable to continue."
-      exit 2
-  fi
-
-  # If we get here, the key is good.
-  echo "Key is valid"
 
   # This next will fail if testing on development machines, which is "a good thing"
   echo "Installing sources list"
