fix to activation
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/alpine@3368 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/mvactivate b/mvvm/hier/usr/bin/mvactivate
--- a/mvvm/hier/usr/bin/mvactivate
+++ b/mvvm/hier/usr/bin/mvactivate
@@ -11,13 +11,13 @@ fi
 
 $KEY_VERIFICATION $REG_KEY 2> /dev/null
 VERIFY_RES="$?"
-if [ "$VERIFY_RES" -eq 127 ]; then
-    echo "Error validating registration.  Unable to continue."
-    exit 2
-fi
-if [ "$VERIFY_RES" -ne 1 ]; then
+if [ "$VERIFY_RES" -eq 1 ]; then
     echo "Key is invalid: $REG_KEY"
     exit 1
+fi
+if [ "$VERIFY_RES" -ne 0 ]; then
+    echo "Error validating registration.  Unable to continue."
+    exit 2
 fi
 
 # If we get here, the key is good.
