chunk 2 of reports
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/alpine@7508 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/mvvm/hier/usr/bin/update-reports b/mvvm/hier/usr/bin/update-reports
--- a/mvvm/hier/usr/bin/update-reports
+++ b/mvvm/hier/usr/bin/update-reports
@@ -1,9 +1,20 @@
 #!/bin/sh
 
+if [ $# -gt 1 ]; then
+    echo "Usage: update-reports [ yyyy-mm-dd ]"
+    echo "  If date specified, assume generating for midnight on that day (ie: 2006-04-09)"
+    exit 1
+fi
+#
+
 REPORT_TYPE_MARK="REPORT_TYPE_MARK"
 IS_DETAILED_MARK="IS_DETAILED_MARK"
 EMAIL_BASE_NAME="${REPORT_TYPE_MARK}_${IS_DETAILED_MARK}"
 
+midnight=$(date +%F)
+if [ $# -eq 1 ]; then
+    midnight=$1
+fi
 
 ## Parameters:
 ## <type> : daily, weekly or monthly
@@ -67,26 +78,23 @@ function exitOnMvvmError()
     fi
 }
 
-JAVA_HOME=${JAVA_HOME:-/opt/java}
-
-# Need bootstrap for logging stuff...  XXX
-CLASSPATH="@MVVM_LIB@/mvvm-bootstrap.jar:@MVVM_LIB@/mvvm-reporting.jar:@MVVM_LIB@/mvvm-impl.jar:@MVVM_LIB@/mvvm-api.jar:@MVVM_WEB@/webstart/metavize-client-api.jar:@MVVM_WEB@/webstart/metavize-client-impl.jar"
-for f in @THIRDPARTY_REPORTS_LIB@/*jar ; do
-    CLASSPATH="$CLASSPATH:$f"
-done
-
-# Use 16Meg of memory for sorting, 32Meg for vacuuming, assume 30Meg of linux caching
+# Use 16Meg of memory for sorting, 64Meg for vacuuming, assume 90Meg of linux caching
 # (tilts optimizer towards use of indices)
-PGOPTIONS="-c sort_mem=16384 -c vacuum_mem=32768 -c effective_cache_size=3000"
+PGOPTIONS="-c sort_mem=16384 -c vacuum_mem=65536 -c effective_cache_size=9000"
 
-export JAVA_HOME CLASSPATH PGOPTIONS
+export PGOPTIONS
 
 REPORT_DIR=@MVVM_WEB@/reports
 
+################################################################################
+# CLEANUP SECTION
 # roll up logs, deleting any more than 31 days old (and thus unreportable  on)
-@USR_BIN@/rollup-logs 31
+@USR_BIN@/rollup-logs $midnight 31
 
 echo "VACUUM ANALYZE;" | psql -U metavize mvvm
+
+# END CLEANUP SECTION
+################################################################################
 
 rm -rf $REPORT_DIR/current
 # Just in case left over (we use a jsp now)
@@ -100,37 +108,35 @@ exitOnMvvmError $? mvvm
 
 # Only generate today's reports if the reporting transform is running
 if [ $is_reporting_enabled == 'true' ]; then
-    mars=$(@USR_BIN@/mcli instances | grep -i running | awk '{print $2}' | uniq | sed 's|^\(.*\)$|@MVVM_TOOLBOX@/\1-impl.jar|')
-    exitOnMvvmError $? mvvm
 
     # Build the DHCP Merged Address Map (needed for running start-reports scripts)
-    MEM=$(awk '/MemTotal/ { print $2 }' < /proc/meminfo)    
-    if [ MEM -gt 1000000 ] ; then
-      MAX_HEAP_SIZE=512m
-    else
-      MAX_HEAP_SIZE=200m
-    fi
-    
-    $JAVA_HOME/bin/java -Xmx${MAX_HEAP_SIZE} \
-        -Dlog4j.configuration=file:@MVVM_HOME@/conf/log4j-reporter.xml \
-        com.metavize.mvvm.reporting.Reporter -o $REPORT_DIR -d 32 -m "$@"
+    @USR_BIN@/mcli -t 3600 prepareReports -o $REPORT_DIR -d 90 -n $midnight
     exitOnMvvmError $? reporter
+    # note that Reporter has just created settings.env and daystoadd
 
-    # Build pre-joined reports tables
-    for c in @MVVM_SCHEMA@/*/start-reports.sql; do
-        psql -U metavize -f $c mvvm
-    done
-
-    echo "VACUUM ANALYZE;" | psql -U metavize mvvm
-
-    $JAVA_HOME/bin/java -Xmx${MAX_HEAP_SIZE} \
-        -Dlog4j.configuration=file:@MVVM_HOME@/conf/log4j-reporter.xml \
-        com.metavize.mvvm.reporting.Reporter -o $REPORT_DIR -d 32 "$@" $mars
-    exitOnMvvmError $? reporter
-    # note that Reporter has just created settings.env
-
-    if [ -h $REPORT_DIR/current ]; then
+    if [ -h $REPORT_DIR/current -a -f $REPORT_DIR/current/daystoadd ]; then
         source $REPORT_DIR/current/settings.env
+
+        # Build pre-joined reports tables
+        while read dayname daybegin dayend; do
+            for c in @MVVM_SCHEMA@/*/report-add-day.sql; do
+                psql -U metavize -v dayname="$dayname" -v daybegin="'$daybegin'" -v dayend="'$dayend'" -f $c mvvm
+            done
+            psql -U metavize -v dayname="'$dayname'" -v daybegin="'$daybegin'" mvvm <<EOF
+insert into reports.report_data_days values (:dayname, DATE :daybegin);
+EOF
+        done < $REPORT_DIR/current/daystoadd
+
+        echo "ANALYZE;" | psql -U metavize mvvm
+
+        @USR_BIN@/mcli -t 3600 startReports
+        exitOnMvvmError $? reporter
+
+        is_running=$(@USR_BIN@/mcli isReportingRunning)
+        while [ $is_running != 'false' ]; do
+            sleep 5
+            is_running=$(@USR_BIN@/mcli isReportingRunning)
+        done
 
         cp -pr $REPORT_DIR/css $REPORT_DIR/current
         cp -pr $REPORT_DIR/images $REPORT_DIR/current
@@ -186,11 +192,8 @@ if [ $is_reporting_enabled == 'true' ]; then
         fi
     fi
 
-    for c in @MVVM_SCHEMA@/*/finish-reports.sql; do
-        psql -U metavize -f $c mvvm
-    done
-
-    echo "VACUUM ANALYZE;" | psql -U metavize mvvm
+# No need for this at the end anymore.
+#    echo "VACUUM ANALYZE;" | psql -U metavize mvvm
 else
     echo "reporting is disabled"
 fi
