a little shifting around.
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/src@16566 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/uvm/hier/usr/share/untangle/bin/bunnicula b/uvm/hier/usr/share/untangle/bin/bunnicula
--- a/uvm/hier/usr/share/untangle/bin/bunnicula
+++ b/uvm/hier/usr/share/untangle/bin/bunnicula
@@ -35,8 +35,10 @@ fi
 if [ ! -f /proc/net/netfilter/nfnetlink_queue ]; then
     echo "ERROR: kernel does not have IP_NF_QUEUE" >& 2
     exit 1
-elif [ "`cat /proc/net/netfilter/nfnetlink_queue | wc -l`x" != "0x" ] ; then
-    echo "ERROR: nfqueue allocated, exiting" >&2
+
+queue_owner=`awk -v queue=0 '{ if ( $1 == queue ) print $2 }' /proc/net/netfilter/nfnetlink_queue `
+elif [ -n "${queue_owner}" ] ; then
+    echo "ERROR: nfqueue allocated by (${queue_owner}), exiting" >&2
     exit 1
 fi
 
