fixes for 2.6.24: don't allow ip_queue module
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/src@14574 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/uvm/hier/usr/share/untangle/bin/bunnicula b/uvm/hier/usr/share/untangle/bin/bunnicula
--- a/uvm/hier/usr/share/untangle/bin/bunnicula
+++ b/uvm/hier/usr/share/untangle/bin/bunnicula
@@ -40,10 +40,10 @@ elif [ "`cat /proc/net/netfilter/nfnetlink_queue | wc -l`x" != "0x" ] ; then
     exit 1
 fi
 
-# also check ip_queue
-/sbin/modprobe -q ip_queue
-if [ -f /proc/net/ip_queue ] && [ "`grep Peer /proc/net/ip_queue  | awk '{ print $4 }'`" != "0" ]; then
-    echo "ERROR: ip_queue allocated, exiting" >&2
+# also check that there is no ip_queue.  2.6.24 can't handle.
+/sbin/modprobe -q -r ip_queue
+if [ -f /proc/net/ip_queue ]; then
+    echo "ERROR: ip_queue loaded, exiting" >&2
     exit 1
 fi
 
@@ -58,9 +58,6 @@ procset /proc/sys/vm/swappiness 5
 procset /proc/sys/net/ipv4/tcp_synack_retries 0
 procset /proc/sys/net/ipv4/tcp_syncookies 1
 procset /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait 30
-
-## not sure if this is still applicable since we now use nfqueue, (rbs 9/29/06)
-procset /proc/sys/net/ipv4/ip_queue_maxlen 16384
 
 # remove tomcat persisted sessions
 find @PREFIX@ -name SESSIONS.ser -exec rm -f '{}' ';'
