mkg in ruby
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/src@12507 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/uvm/hier/usr/share/untangle/bin/mkg b/uvm/hier/usr/share/untangle/bin/mkg
--- a/uvm/hier/usr/share/untangle/bin/mkg
+++ b/uvm/hier/usr/share/untangle/bin/mkg
@@ -1,158 +1,267 @@
-#!/bin/sh
+#!/usr/bin/ruby
 
-exec 2>&1
+require 'fileutils'
+require 'getoptlong'
+require 'tempfile'
 
-prefix=@PREFIX@
-APT_LOG=@PREFIX@/var/log/uvm/apt.log
+ENV['DEBIAN_FRONTEND'] = 'noninteractive'
 
-# this is needed now !
-export DEBIAN_FRONTEND=noninteractive
+INST_OPTS = " -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken --purge "
+UPGD_OPTS = " -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken --purge "
+UPDT_OPTS = " --yes --force-yes --purge "
+REMO_OPTS = " --yes --force-yes --fix-broken --purge "
 
-INST_OPTS=" -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken --purge "
-UPGD_OPTS=" -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken --purge "
-UPDT_OPTS=" --yes --force-yes --purge "
-REMO_OPTS=" --yes --force-yes --fix-broken --purge "
-DEBUG_OPTS=" -o Debug::pkgDPkgPM=true "
-RET=0
+PREFIX = "@PREFIX@"
 
-printusage()
-{
-    echo "usage:"
-    echo "mkg installed"
-    echo "mkg available"
-    echo "mkg install <mackage>"
-    echo "mkg update"
-    echo "mkg upgrade"
-    echo "mkg remove"
-    exit 1
-}
+STDERR.reopen('@UVM_LOG@/apt.log', 'a')
 
-aptlog()
-{
-        echo -e "----------" >>$APT_LOG
-        while [ 0 -lt $# ]; do
-            echo $1 >>$APT_LOG
-            shift
-        done
-        date >>$APT_LOG
-        echo -e "----------\n" >>$APT_LOG
-}
+def printusage()
+  puts <<STR
+usage:
+  mkg installed
+  mkg available
+  mkg install <mackage>
+  mkg update
+  mkg upgrade
+  mkg remove
+STR
+end
 
-my_dpkg_query()
-{
-    PKGS="`dpkg --get-selections "$1" | egrep -w 'install$' | awk '{print $1}'`"
-    if [ ! -z "$PKGS" ] ; then
-        echo "$PKGS" | xargs dpkg-query -W
-    fi
-}
+def log(str)
+  STDERR.puts(str)
+  STDERR.flush
+end
 
-download()
-{
-    aptlist=$1
+class DevMkg
+  def initialize(stamp)
+    @pkg_list_dir = "#{PREFIX}/tmp"
+    @stamp = stamp
+  end
 
-    cat $aptlist >>$APT_LOG
-    echo "END PACKAGE LIST" >>$APT_LOG
+  def installed()
+    each_pkg_list_line { |l| puts "#{l.split[1]} 10.0" if /^Package: / =~ l }
+    0
+  end
 
-    for u in $(cat $aptlist | awk '{ print $1 }' | sed "s/'//g"); do
-        echo "downloading: $u" >>$APT_LOG
-        dltmp=$(mktemp -d mkg.XXXXXXXXXX)
-        wget --progress=dot -P "$dltmp" "$u" >>$APT_LOG 2>&1
-        if [ $? -eq 0 ]; then
-            mv $dltmp/* /var/cache/apt/archives
-            echo "DOWNLOAD SUCCEEDED: $u" >>$APT_LOG
-        else
-            echo "DOWNLOAD FAILED: $u" >>$APT_LOG
-        fi
-        rm -r $dltmp
-    done
-}
+  def available()
+    each_pkg_list_line do |l|
+      puts l unless /^XB-/ =~ l
+      puts "Version: 10.0" if /^Package: / =~ l
+    end
+    0
+  end
 
-while getopts k: f; do
-  case $f in
-      k) stamp=$OPTARG
-  esac
-done
-shift $(expr $OPTIND - 1)
+  def install(name)
+    log "start $stamp"
+    log "END PACKAGE LIST"
+    log "done $stamp"
+    0
+  end
 
-if [ $# -lt 1 ] ; then
-    printusage
-fi
+  def update()
+    0
+  end
 
-if [ -z $prefix ] ; then
-    # invoked in real environment
-    if [ "$1" = "installed" ] ; then
-        my_dpkg_query '*' 2>/dev/null | awk '{ if ($2) printf("%s %s\n",$1,$2) }'
-        #RET=$? return code ignored
-    elif [ "$1" = "available" ] ; then
-        pkgs=$(apt-cache search '.' 2>/dev/null | cut -d ' ' -f 1)
-        for pkg in $pkgs; do
-            apt-cache show --no-all-versions $pkg 2>/dev/null
-            #RET=$? return code ignored
-        done
-    elif [ "$1" = "install" ] ; then
-        aptlog "start $stamp"
+  def upgrade()
+    log "start $stamp"
+    log "END PACKAGE LIST" >>$APT_LOG
+    log "done $stamp"
+    0
+  end
 
-        aptlog "downloading: \"$2\""
+  def remove(pkg)
+    0
+  end
 
-        # XXX the way i create mackage name is wrong:
-        aptlist=$(mktemp -t mkg.XXXXXXXXXX)
-        apt-get install $INST_OPTS --print-uris "$2" 2>/dev/null \
-            | awk " /^'http:\\/\\// { print \$0 } " >$aptlist
-        download $aptlist
-        rm $aptlist
+  private
 
-        aptlog "installing: \"$2\""
-        # XXX the way i create mackage name is wrong:
-        apt-get install $INST_OPTS "$2" >>$APT_LOG 2>&1
-        RET=$?
+  def each_pkg_list_line()
+    Dir.new(@pkg_list_dir).select { |d| /^pkg-list/ =~ d }.each do |p|
+      File.open("#{@pkg_list_dir}/#{p}", 'r') do |io|
+        io.each_line { |l| yield l }
+      end
+    end
+  end
+end
 
-        aptlog "done $stamp"
+class RealMkg
+  def initialize(stamp)
+    @stamp = stamp
+  end
 
-    elif [ "$1" = "update" ] ; then
-        aptlog "start $tstamp" "apt-get update $UPDT_OPTS"
-        apt-get update $UPDT_OPTS >>$APT_LOG 2>&1
-        RET=$?
-        aptlog "done $stamp"
-    elif [ "$1" = "upgrade" ] ; then
-        aptlog "start $stamp"  "apt-get upgrade $UPGD_OPTS"
+  def installed()
+    IO.popen("dpkg --get-selections 'untangle*'", 'r') do |input|
+      IO.popen("xargs dpkg-query -W", 'w') do |output|
+        input.each_line do |l|
+          s = l.split
+          output.puts(s[0]) if 'install' == s[1]
+        end
+      end
+    end
+    0
+  end
 
-        aptlist=$(mktemp -t mkg.XXXXXXXXXX)
-        apt-get dist-upgrade $UPGD_OPTS --print-uris 2>/dev/null \
-            | awk " /^'http:\\/\\// { print \$0 } " >$aptlist
-        download $aptlist
-        rm $aptlist
+  def available()
+    IO.popen("apt-cache search '^untangle-'") do |input|
+      IO.popen("xargs apt-cache show --no-all-versions", 'w') do |output|
+        input.each_line do |l|
+          output.puts(l.split[0])
+        end
+      end
+    end
+    0
+  end
 
-        apt-get dist-upgrade $UPGD_OPTS >>$APT_LOG 2>&1
-        RET=$?
+  def install(pkg)
+    log "start #{@stamp}"
+    log "downloading: \"#{pkg}\""
+    pkg_list = get_pkg_list("apt-get install #{INST_OPTS} --print-uris #{pkg}")
+    download(pkg, pkg_list)
+    log "installing: \"#{pkg}\""
 
-        aptlog "done $stamp"
-    elif [ "$1" = "remove" ] ; then
-        aptlog "start $stamp" "apt-get remove $REMO_OPTS \"$2\""
-        apt-get remove $REMO_OPTS "$2" >>$APT_LOG 2>&1
-        apt-get clean >>/dev/null 2>&1
-        RET=$?
-        aptlog "done $stamp"
-    fi
-else
-    # invoked in development environment
-    if [ "$1" = "installed" ] ; then
-        cat $prefix/tmp/pkg-list* | awk ' /^Package: / { print $2 " 10.0" } '
-    elif [ "$1" = "install" ] ; then
-        aptlog "start $stamp"
-        echo "END PACKAGE LIST" >>$APT_LOG
-        aptlog "done $stamp"
-    elif [ "$1" = "update" ] ; then
-        : # XXX
-    elif [ "$1" = "upgrade" ] ; then
-        aptlog "start $stamp"
-        echo "END PACKAGE LIST" >>$APT_LOG
-        aptlog "done $stamp"
-    elif [ "$1" = "remove" ] ; then
-        echo "remove not supported in build environment"
-    elif [ "$1" = "available" ] ; then
-        cat $prefix/tmp/pkg-list* | sed -e 's/^XB-//' \
-            | awk '{ print $0 }; /^Package: / { print "Version: 10.0" }'
-    fi
-fi
+    IO.popen("apt-get install #{INST_OPTS} #{pkg}", 'r') do |input|
+      input.each_line { |l| log l }
+    end
+    r = $?
 
-exit $RET
+    log "done #{@stamp}"
+
+    r
+  end
+
+  def update()
+    log "start #{@stamp}"
+    log "apt-get update #{UPDT_OPTS}"
+    IO.popen("apt-get update #{UPDT_OPTS}") do |io|
+      io.each_line { |l| log l }
+    end
+
+    r = $?
+
+    log "done #{@stamp}"
+
+    0
+  end
+
+  def upgrade()
+    log "start #{@stamp}"
+    log "apt-get upgrade #{UPGD_OPTS}"
+
+    pkg_list = get_pkg_list("apt-get dist-upgrade #{UPGD_OPTS} --print-uris")
+    download(pkg_list)
+    r = cmd_to_stderr("apt-get dist-upgrade #{UPGD_OPTS}")
+
+    log "done #{@stamp}"
+
+    0
+  end
+
+  def remove(pkg)
+    log "start #{@stamp}"
+    log "apt-get remove #{REMO_OPTS} \"$2\""
+    r = cmd_to_stderr("apt-get remove #{REMO_OPTS}")
+    cmd_to_stderr("apt-get clean")
+    log "done #{@stamp}"
+
+    0
+  end
+
+  private
+
+  def cmd_to_stderr(cmd)
+    IO.popen(cmd) do |io|
+      io.each_line { |l| log l }
+    end
+    $?
+  end
+
+    def get_tempdir()
+      tmp = Tempfile.new('mkg')
+      path = tmp.path
+      tmp.delete
+      Dir.mkdir(path)
+      Dir.new(path)
+    end
+
+    def get_pkg_list(apt_cmd)
+      pkg_list = []
+
+      IO.popen(apt_cmd, 'r') do |io|
+        io.each_line do |l|
+          if /^'(http:\/\/.*)' / =~ l
+            pkg_list << $1
+          end
+        end
+      end
+
+      pkg_list
+    end
+
+    def download(pkg, pkg_list)
+      pkg_list.each { |p| log p }
+      log "END PACKAGE LIST"
+
+      tmp_dir = get_tempdir()
+      begin
+        pkg_list.each do |p|
+          log "downloading: #{p}"
+
+          cmd_to_stderr("wget --progress=dot -P #{tmp_dir.path} #{p} 2>&1")
+
+          if $?.success?
+            tmp_dir.select { |f| /\.deb$/ =~ f }.each do |f|
+              FileUtils.mv("#{tmp_dir.path}/#{f}", "/var/cache/apt/archives")
+            end
+            log "DOWNLOAD SUCCEEDED: #{pkg}"
+          else
+            log "DOWNLOAD FAILED: #{pkg}"
+          end
+
+        end
+      ensure
+        FileUtils.rm_rf(tmp_dir.path)
+      end
+    end
+
+  end
+
+  stamp = nil
+
+  opts = GetoptLong.new([ '-k', GetoptLong::REQUIRED_ARGUMENT ])
+  opts.each do |opt, arg|
+    if '-k' == opt
+      stamp = arg
+    end
+  end
+
+  if ARGV.length < 1
+    printusage()
+    exit(1)
+  end
+
+  ret = 0
+
+  mkg = PREFIX.empty? ? RealMkg.new(stamp) : DevMkg.new(stamp)
+
+  exit case ARGV.shift
+  when 'installed'
+    mkg.installed()
+  when 'available'
+    mkg.available()
+  when 'install'
+    if ARGV.empty?
+      printusage()
+    else
+      mkg.install(ARGV.shift)
+    end
+  when 'update'
+    mkg.update()
+  when 'upgrade'
+    mkg.upgrade()
+  when 'remove'
+    if ARGV.empty?
+      printusage()
+    else
+      mkg.remove(ARGV.shift)
+    end
+  end
