Allow (temporary) activation for CD installs.
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/src@16500 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/uvm/hier/usr/share/untangle/bin/utactivate b/uvm/hier/usr/share/untangle/bin/utactivate
--- a/uvm/hier/usr/share/untangle/bin/utactivate
+++ b/uvm/hier/usr/share/untangle/bin/utactivate
@@ -7,16 +7,18 @@ REG_KEY="$1"
 if [ -n "$REG_KEY" ] ; then # the install wizard is calling us
   echo $REG_KEY > $ACTIVATION_KEY_FILE
 
-  $KEY_VERIFICATION $REG_KEY 2> /dev/null
-  VERIFY_RES="$?"
-  if [ "$VERIFY_RES" -eq 1 ]; then
-    echo "Key is invalid: $REG_KEY"
-    rm -f $ACTIVATION_KEY_FILE
-    exit 1
-  elif [ "$VERIFY_RES" -ne 0 ]; then
-    echo "Error validating registration.  Unable to continue."
-    rm -f $ACTIVATION_KEY_FILE
-    exit 2
+  if [[ $REG_KEY != $FAKE_KEY ]] ; then
+    $KEY_VERIFICATION $REG_KEY 2> /dev/null
+    VERIFY_RES="$?"
+    if [ "$VERIFY_RES" -eq 1 ]; then
+      echo "Key is invalid: $REG_KEY"
+      rm -f $ACTIVATION_KEY_FILE
+      exit 1
+    elif [ "$VERIFY_RES" -ne 0 ]; then
+      echo "Error validating registration.  Unable to continue."
+      rm -f $ACTIVATION_KEY_FILE
+      exit 2
+    fi
   fi
 
   # If we get here, the key is good.
