Partial fix for the openvpn not restarting on upgrade.  Closes: #6771
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/work/src@24527 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/openvpn/hier/usr/share/untangle/openvpn/start-openvpn b/openvpn/hier/usr/share/untangle/openvpn/start-openvpn
--- a/openvpn/hier/usr/share/untangle/openvpn/start-openvpn
+++ b/openvpn/hier/usr/share/untangle/openvpn/start-openvpn
@@ -16,8 +16,7 @@ else
 fi
 
 RETRY_ATTEMPTS=5
-RESTART_DELAY=1
-
+RESTART_DELAY=2
 
 TUN_DEVICE=/dev/net/tun
 
@@ -26,6 +25,12 @@ if [ ! -c ${TUN_DEVICE} ]; then
     mkdir -p /dev/net
     mknod ${TUN_DEVICE} c 10 200
 fi
+
+start_vpn_server()
+{
+    ## This will print fail if the script returns non-zero
+    /etc/init.d/openvpn start || echo fail
+}
 
 ## This is always disabled so the server never starts at system startup.
 disableOpenVPNStartup
@@ -60,7 +65,11 @@ echo "[`date`,start-openvpn] Starting the openvpn server"
 ## This is required or else openvpn won't restart properly (sometimes the UDP port is still bound)
 for (( t = 0 ; t < ${RETRY_ATTEMPTS} ; t++ )); do
     ## These script don't return a non-zero value
-    [ -z "`${OPENVPN_SCRIPT} start | grep FAILED`" ] && true && break
+    start_vpn_server 2>&1 | grep fail > /dev/null 2>&1 || {
+        echo "[`date`,start-openvpn] Successfully started openvpn daemon"
+        exit 0
+    }
+
     echo "[`date`,start-openvpn] Unable to start openvpn daemon, waiting ${RESTART_DELAY} seconds"
 
     ## Just in case, kill all openvpn instances
