ngfw-15150 - draft pr to support openvpn inline support

diff --git a/openvpn/hier/usr/share/untangle/bin/openvpn-import-config b/openvpn/hier/usr/share/untangle/bin/openvpn-import-config
--- a/openvpn/hier/usr/share/untangle/bin/openvpn-import-config
+++ b/openvpn/hier/usr/share/untangle/bin/openvpn-import-config
@@ -21,56 +21,93 @@ if [ ! -f "${filename}" ]; then
     exit -1
 fi
 
-TMPDIR=`mktemp -d || exit -3`
 
-unzip -q ${filename} -d ${TMPDIR} || { rm -rf ${TMPDIR};  exit -1 ; }
+ext="${filename##*.}"
 
-CONFNAME="`ls ${TMPDIR}/untangle-vpn/*.conf`"
+case "$ext" in
+    zip)
+        TMPDIR=`mktemp -d || exit -3`
 
-if [ -z "$CONFNAME" ] ; then
-    echo "Missing conf file"
-    exit -1
-fi
+        unzip -q ${filename} -d ${TMPDIR} || { rm -rf ${TMPDIR};  exit -1 ; }
 
-SITENAME="`basename $CONFNAME | sed -e 's/.conf//'`"
+        CONFNAME="`ls ${TMPDIR}/untangle-vpn/*.conf`"
 
-# echo sitename to stdout
-# This is important because the java code launching this script
-# will use this to determine the site name. Do not remove.
-echo "SiteName: ${SITENAME}" 
+        if [ -z "$CONFNAME" ] ; then
+            echo "Missing conf file"
+            exit -1
+        fi
 
-if [ -z "$SITENAME" ] ; then
-    echo "Missing site name"
-    exit -1
-fi
+        SITENAME="`basename $CONFNAME | sed -e 's/.conf//'`"
 
-## Copy in the necessary files
-mkdir -p @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/
-mkdir -p @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/keys/
+        # echo sitename to stdout
+        # This is important because the java code launching this script
+        # will use this to determine the site name. Do not remove.
+        echo "SiteName: ${SITENAME}" 
 
-CONF_FILE="@PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/${SITENAME}.conf"
+        if [ -z "$SITENAME" ] ; then
+            echo "Missing site name"
+            exit -1
+        fi
 
-cp ${TMPDIR}/untangle-vpn/*.conf ${CONF_FILE}
+        ## Copy in the necessary files
+        mkdir -p @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/
+        mkdir -p @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/keys/
 
-if [ $? != 0 ] ; then
-    echo "Copy failed"
-    cleanup
-fi
+        CONF_FILE="@PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/${SITENAME}.conf"
 
-if [ -d ${TMPDIR}/untangle-vpn/keys ] ; then
-    cp -r ${TMPDIR}/untangle-vpn/keys/* @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/keys/
-fi
+        cp ${TMPDIR}/untangle-vpn/*.conf ${CONF_FILE}
 
-if [ $? != 0 ] ; then
-    echo "Key Copy failed"
-    echo ${TMPDIR}
-    exit
-    cleanup
-fi
+        if [ $? != 0 ] ; then
+            echo "Copy failed"
+            cleanup
+        fi
 
-## Cleanup
-rm -rf ${TMPDIR}
+        if [ -d ${TMPDIR}/untangle-vpn/keys ] ; then
+            cp -r ${TMPDIR}/untangle-vpn/keys/* @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/keys/
+        fi
 
-echo "New configuration imported: ${CONF_FILE}"
+        if [ $? != 0 ] ; then
+            echo "Key Copy failed"
+            echo ${TMPDIR}
+            exit
+            cleanup
+        fi
 
-true
+        ## Cleanup
+        rm -rf ${TMPDIR}
+
+        echo "New configuration imported: ${CONF_FILE}"
+
+        true
+        ;;
+
+    ovpn)
+        SITENAME=$(basename "${filename}" .ovpn)
+        echo "FILENAME : ${filename}"
+        echo "SiteName: ${SITENAME}"
+
+        if [ -z "$SITENAME" ]; then
+            echo "Missing site name"
+            exit -1
+        fi
+
+        mkdir -p @PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/
+
+        CONF_FILE="@PREFIX@/usr/share/untangle/settings/openvpn/remote-servers/${SITENAME}.conf"
+
+        cp "${filename}" "${CONF_FILE}"
+
+        if [ $? != 0 ] ; then
+            echo "Failed to copy .ovpn file"
+            exit -1
+        fi
+
+        echo "Inline .ovpn configuration imported: ${CONF_FILE}"
+        true
+        ;;
+
+    *)
+        echo "Unsupported file format: .$ext"
+        exit 2
+        ;;
+esac
